# Generated by Django 2.2.6 on 2020-01-04 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='evaluation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='auther',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='impression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='isbn',
            field=models.TextField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
