# Generated by Django 2.2.6 on 2020-01-04 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmemo', '0002_auto_20200104_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='evaluation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
